name: SonarCloud
on:
  push:
    paths:
      - "LambdaF4/**"
      - ".github/workflows/Lambda4.yaml"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v1.8
        with:
          projectBaseDir: LambdaF4
          args: >
            -Dsonar.organization=aartitestorganization
            -Dsonar.projectKey=aartitestorganization_monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
