name: SonarCloud
on:
  push:
    paths:
      - "LambdaF3/**"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v1.8
        with:
          args: >
            -Dsonar.organization=cyabge-koredevdata
            -Dsonar.projectKey=cyabge-koredevdata_pythonmonorepolambdafunction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
